# Generated by Django 4.0 on 2023-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_into', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poster',
            field=models.CharField(max_length=500),
        ),
    ]
